name: Tippy
options:
  bundleIdPrefix: com.tippy
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_KEY_UILaunchScreen_Generation: true
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_CFBundleDisplayName: Tippy
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

schemes:
  Tippy:
    build:
      targets:
        Tippy: all
    run:
      storeKitConfiguration: Tippy/Configuration.storekit

targets:
  Tippy:
    type: application
    platform: iOS
    sources:
      - path: Tippy/Sources
      - path: Tippy/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tippy.app
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: Tippy
        INFOPLIST_KEY_NSCameraUsageDescription: "Tippy uses your camera to scan receipts and read the bill total."
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Tippy uses your approximate location to tailor tip recommendations to local customs."
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
    postCompileScripts:
      - script: |
          if [ -f "${SRCROOT}/.env" ]; then
            source "${SRCROOT}/.env"
            /usr/libexec/PlistBuddy -c "Add :CLAUDE_API_KEY string ${CLAUDE_API_KEY}" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}" 2>/dev/null || \
            /usr/libexec/PlistBuddy -c "Set :CLAUDE_API_KEY ${CLAUDE_API_KEY}" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
          fi
        name: Inject API Key
