name: Tippy
options:
  bundleIdPrefix: com.tippy
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_KEY_UILaunchScreen_Generation: true
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_CFBundleDisplayName: Tippy
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

targets:
  Tippy:
    type: application
    platform: iOS
    sources:
      - path: Tippy/Sources
      - path: Tippy/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tippy.app
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: Tippy
        INFOPLIST_KEY_NSCameraUsageDescription: "Tippy uses your camera to scan receipts and read the bill total."
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
